platform:ios, '8.0'
#source 'https://git.oschina.net/2tiger/TT_YTKNetwork.git'

target 'zhike' do

pod 'AFNetworking', '~> 3.0'
pod 'MJExtension'
pod 'YTKNetwork'

pod 'YYCache'
#pod 'YYModel', '~> 1.0.4'
#pod 'MyLayout', '~> 1.5.0'
#pod 'YTKKeyValueStore', '~> 0.1.2'
#pod 'MLeaksFinder', '~> 0.2.1'
#pod 'AsyncDisplayKit', '~> 2.1'
#pod 'CocoaLumberjack','~> 3.2.1'
#pod 'pop'
#pod 'YTKKeyValueStore', '~> 0.1.2'
pod 'SDWebImage','~>4.0.0'
#pod 'SDWebImage/GIF'
#pod 'DZNEmptyDataSet', '~> 1.8.1'
#pod 'MJRefresh', '~> 3.1.12'

end
